using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.Nuke.UI;

[GenerateTypedNameReferences]
public sealed partial class MCNukeWindow : DefaultWindow
{
    public MCNukeWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTime(TimeSpan time)
    {
        TimeLabel.Text = $"{time}s";
    }

    public void SetSettingsVisible(bool value)
    {
        SettingsBoxContainer.Visible = value;
    }

    public void SetSettingsAnchored(bool value)
    {
        AnchorButton.Text = value ? "Unanchor" : "Anchor";
    }
}
