using Content.Client._MC.ASRS.UI.Buttons;
using Content.Shared._MC.ASRS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Views;

[GenerateTypedNameReferences]
public sealed partial class MCASRSRequestsView : MCASRSView
{
    private readonly Dictionary<MCASRSRequest, MCASRSRequestButton> _buttons = new();

    public event Action? ApprovedAll;
    public event Action? DenyAll;
    public event Action<MCASRSRequest>? Approved;
    public event Action<MCASRSRequest>? Denied;

    private bool _interactable = true;

    public IReadOnlyDictionary<MCASRSRequest, MCASRSRequestButton> Buttons => _buttons;

    public MCASRSRequestsView()
    {
        RobustXamlLoader.Load(this);

        ApproveAllButton.OnPressed += _ => ApprovedAll?.Invoke();
        DenyAllButton.OnPressed += _ => DenyAll?.Invoke();
    }

    public void Reinitialize(bool interactable)
    {
        _interactable = interactable;
        InteractionContainer.Visible = _interactable;
    }

    public void Refresh(MCASRSBui bui, IReadOnlyList<MCASRSRequest> requests)
    {
        ApproveAllButton.Disabled = bui.RequestsTotalCost == 0;

        _buttons.Clear();

        Container.Children.Clear();
        foreach (var request in requests)
        {
            var button = new MCASRSRequestButton(request,
                OnApproved,
                OnDenied,
                bui.Points < request.TotalCost,
                interactable: _interactable);

            Container.AddChild(button);

            _buttons.Add(request, button);
        }
    }

    private void OnApproved(MCASRSRequest request)
    {
        Approved?.Invoke(request);
    }

    private void OnDenied(MCASRSRequest request)
    {
        Denied?.Invoke(request);
    }
}
