using Content.Client._MC.ASRS.UI.Buttons;
using Content.Shared._MC.ASRS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Views;

[GenerateTypedNameReferences]
public sealed partial class MCASRSRequestsView : MCASRSView
{
    public event Action? ApprovedAll;
    public event Action? DenyAll;
    public event Action<MCASRSRequest>? Delivered;
    public event Action<MCASRSRequest>? Approved;
    public event Action<MCASRSRequest>? Denied;

    private bool _interactable = true;
    private bool _deliverable;

    public MCASRSRequestsView()
    {
        RobustXamlLoader.Load(this);

        ApproveAllButton.OnPressed += _ => ApprovedAll?.Invoke();
        DenyAllButton.OnPressed += _ => DenyAll?.Invoke();
    }

    public void Reinitialize(bool interactable, bool deliverable = false)
    {
        _interactable = interactable;
        _deliverable = deliverable;

        InteractionContainer.Visible = _interactable;
    }

    public void Refresh(MCASRSBui bui, IReadOnlyList<MCASRSRequest> requests)
    {
        ApproveAllButton.Disabled = bui.RequestsTotalCost == 0;

        Container.Children.Clear();
        foreach (var request in requests)
        {
            var button = new MCASRSRequestButton(request,
                OnApproved,
                OnDenied,
                OnDelivered,
                bui.Points < request.TotalCost,
                interactable: _interactable,
                deliverable: _deliverable);

            Container.AddChild(button);
        }
    }

    private void OnApproved(MCASRSRequest request)
    {
        Approved?.Invoke(request);
    }

    private void OnDenied(MCASRSRequest request)
    {
        Denied?.Invoke(request);
    }

    private void OnDelivered(MCASRSRequest request)
    {
        Delivered?.Invoke(request);
    }
}
