using Content.Client._MC.ASRS.UI.Buttons;
using Content.Shared._MC.ASRS.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Views;

[GenerateTypedNameReferences]
public sealed partial class MCASRSPendingOrdersView : MCASRSView
{
    public event Action<string>? Submitted;
    public event Action? Cleared;
    public event Action<MCASRSEntry, int>? OrderCountChanged;

    private string Reason => ReasonBar.Text;

    public MCASRSPendingOrdersView()
    {
        RobustXamlLoader.Load(this);

        ReasonBar.OnTextChanged += OnReasonChanged;
        SubmitButton.OnPressed += _ => Submitted?.Invoke(Reason);
        ClearButton.OnPressed += _ => Cleared?.Invoke();
    }

    public override void Open(MCASRSBui bui)
    {
        base.Open(bui);
        Refresh(bui);
    }

    public void Refresh(MCASRSBui bui)
    {
        Container.Children.Clear();
        foreach (var (entry, count) in bui.Store)
        {
            Container.Children.Add(new MCASRSOrderButton(entry, count, OnCountChanged));
        }
    }

    private void OnReasonChanged(LineEdit.LineEditEventArgs obj)
    {
        SubmitButton.Disabled = ReasonBar.Text == string.Empty;
    }

    private void OnCountChanged(MCASRSEntry entry, int count)
    {
        OrderCountChanged?.Invoke(entry, count);
    }
}
