using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Views;

[GenerateTypedNameReferences]
public sealed partial class MCASRSCategoryView : MCASRSView
{
    public MCASRSCategoryView()
    {
        RobustXamlLoader.Load(this);
    }

    public void Refresh(MCASRSBui bui)
    {
        PendingOrderButton.Disabled = bui.StoreEmpty;

        PointsLabel.SetMessage(bui.Points.ToString());

        OrdersLabel.SetMessage(bui.RequestsAwaitingDelivery.Count.ToString());
        CostLabel.SetMessage(bui.StoreCost.ToString());
        ItemsLabel.SetMessage(bui.StoreCount.ToString());

        RequestsButton.Disabled = !bui.HasRequests;
        AwaitingDeliveryButton.Disabled = !bui.HasRequestsAwaitingDelivery;
        ApprovedRequestsButton.Disabled = !bui.HasRequestsApprovedHistory;
        DeniedRequestsButton.Disabled = !bui.HasRequestsDeniedHistory;
    }
}
