- type: entity
  parent: CMWeaponPistolBase
  id: MCWeaponPistol
  categories: [ MCContent ]
  abstract: true
  components:
  - type: Tag
    tags:
    - MCWeaponSidearm
    - MCWeaponPistol
  - type: MCAimedShoot
    aimSpeedModifier: 0.65

- type: entity
  parent: RMCWeaponRevolverBase
  id: MCWeaponRevolver
  categories: [ MCContent ]
  abstract: true
  components:
  - type: Tag
    tags:
    - MCWeaponSidearm
    - MCWeaponRevolver
  - type: MCAimedShoot
    aimSpeedModifier: 0.65

- type: Tag
  id: MCWeaponSidearm

- type: Tag
  id: MCMagazineSidearm

- type: Tag
  id: MCWeaponPistol

- type: Tag
  id: MCMagazinePistol

- type: Tag
  id: MCWeaponRevolver

- type: Tag
  id: MCMagazineRevolver
