using Content.Shared._MC.ASRS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.UI.Buttons;

[GenerateTypedNameReferences]
public sealed partial class MCASRSRequestButton : BoxContainer
{
    public MCASRSRequestButton()
    {
        RobustXamlLoader.Load(this);
    }

    public MCASRSRequestButton(MCASRSRequest request, Action<MCASRSRequest> approved, Action<MCASRSRequest> denied, bool approveDisabled, bool interactable = true) : this()
    {
        ApproveButton.Disabled = approveDisabled;

        ApproveButton.OnPressed += _ => approved.Invoke(request);
        DenyButton.OnPressed += _ => denied.Invoke(request);

        RequesterLabel.SetMessage(request.Requester);
        ReasonLabel.SetMessage(request.Reason);
        TotalCostLabel.SetMessage(request.TotalCost.ToString());

        InteractionContainer.Visible = interactable;


        foreach (var (entry, count) in request.Contents)
        {
            var label = new RichTextLabel();
            var message = string.Empty;

            if (count > 0)
                message += $"{count}x";

            message += $"{entry.Name} ({entry.Cost * count})";
            label.SetMessage(message);

            Container.Children.Add(label);
        }
    }
}
