- type: entity
  id: MCXenoStructure
  abstract: true
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: Appearance
  # - type: GuideHelp
  #   guides:
  #   - RMCGuideHiveStructures
  - type: Transform
    anchored: true
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        layer:
        - BulletImpassable
        density: 200
  - type: InteractionOutline
  - type: Clickable
  - type: Damageable
    damageContainer: StructuralXeno
    damageModifierSet: Resin
  - type: RMCNightVisionVisible
    priority: -1
    transparency: 0.2
  - type: XenoConstruct
  - type: XenoFriendly
  - type: XenoAnnounceStructureDestruction
  - type: RequireProjectileTarget
  - type: Flammable
    fireSpread: false
    maximumFireStacks: 0.5
    damage:
      types:
        Heat: 3.8
  - type: Corrodible
    isCorrodible: false

- type: entity
  parent: MCXenoStructure
  id: MCXenoStructureSilo
  name: silo
  description: A disgusting biomass generator that reeks of rotting flesh. Capable of producing parasites on its own.
  components:
  - type: Sprite
    sprite: _MC/Structures/Xeno/silo.rsi
    layers:
    - state: icon
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-1.49,-1.49,1.49,1.49" # 3x3
        density: 200
        mask:
        - ItemMask
        layer:
        - BulletImpassable
  - type: CollisionWake
    enabled: false
  - type: XenoStructureMapTracked
  - type: MCXenoStructureSpawner
    mobsPerPlayer: 0.075
    respawnMultiplier: 2
  - type: TacticalMapTracked
  - type: TacticalMapIcon
    icon:
      sprite: _MC/Interface/Xeno/icons.rsi
      state: silo_passive
  - type: XenoWeedsSpreading
  - type: XenoWeeds
    range: 3
    spawns: MCXenoWeeds
    healOnStopSpreading:
      groups:
        Brute: -6

- type: entity
  parent: MCXenoStructure
  id: MCXenoStructureTowerEvolution
  name: evolution tower
  description: A disgusting biomass generator that reeks of rotting flesh. Capable of producing parasites on its own.
  components:
  - type: Sprite
    sprite: _MC/Structures/Xeno/towers.rsi
    layers:
    - state: evolution
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49" # 1x1
        density: 200
        mask:
        - ItemMask
        layer:
        - BulletImpassable
  - type: CollisionWake
    enabled: false
  # - type: XenoStructureMapTracked
  # - type: TacticalMapTracked
  # - type: TacticalMapIcon
  #   icon:
  #     sprite: _MC/Interface/Xeno/icons.rsi
  #     state: silo_passive

- type: entity
  parent: MCXenoStructure
  id: MCXenoStructureTowerPsychic
  name: psychic tower
  description: A disgusting biomass generator that reeks of rotting flesh. Capable of producing parasites on its own.
  components:
  - type: Sprite
    sprite: _MC/Structures/Xeno/towers.rsi
    layers:
    - state: psychic
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        density: 200
        mask:
        - ItemMask
        layer:
        - BulletImpassable
  - type: CollisionWake
    enabled: false
  # - type: XenoStructureMapTracked
  # - type: TacticalMapTracked
  # - type: TacticalMapIcon
  #   icon:
  #     sprite: _MC/Interface/Xeno/icons.rsi
  #     state: silo_passive
