- type: entity
  parent:
  - MCXenoUnactiveBase
  - MCXenoComponentAI
  - CMXenoDeveloped
  - RMCXenoSpeechSounds
  - RMCXenoCommendationReceiver
  - RMCXenoMobCollision
  id: MCXenoMinion
  abstract: true
