- type: entity
  id: MCFire
  name: fire
  placement:
    mode: SnapgridCenter
  components:
  - type: Tag
    tags:
    - MCDamageFire
    - HideContextMenu
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.35,-0.35,0.35,0.35"
        density: 100
        layer:
        - MobMask
        hard: false
  - type: Sprite
    sprite: _RMC14/Effects/fire.rsi
    noRot: true
    drawdepth: WallTops
    layers:
    - map: [ "base" ]
      state: red_4
  - type: Clickable
  - type: InteractionOutline
  - type: PointLight
    radius: 5
    color: "#bf6d02"
  - type: EffectVisuals
  - type: RMCIgniteOnCollide
    maxStacks: 20
    tileDamage:
      types:
        Heat: 0.5
  - type: DamageOnCollide
    damageDead: false
    fire: true
    damage:
      types:
        Heat: 45
  - type: TileFire
    id: MCFire
    extinguishInstantly: false
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.TileFireLayers.Base:
        base:
          One: { state: red_1 }
          Two: { state: red_2 }
          Three: { state: red_3 }
          Four: { state: red_4 }
  - type: IgnorePredictionHit
  - type: RMCScorchEffectOnSpawn
    decalTag: burnt
    tileLimit: 3
  - type: BlockWeeds

# Flamethrower Я НЕ ПОНИМАЮ БАЛАНС ЭТОЙ ХУЙНИ БЛЯТЬ
- type: entity
  parent: MCFire
  id: MCFlamethrowerFire
  name: fire
  placement:
    mode: SnapgridCenter
  components:
  - type: DamageOnCollide
    damageDead: false
    fire: true
    damage:
      types:
        Heat: 31 # damage = 31
  - type: RMCIgniteOnCollide
    maxStacks: 20 # incendiary_strength = 30, но там учитывается броня так-что 20 будет
    intensity: 31 # burn_level = 31
    duration: 10
    tileDamage:
      types:
        Heat: 0.13
  - type: TileFire
    id: MCFlamethrowerFire
    duration: 17 # burn_time = 17
    extinguishInstantly: false

# Blue Flame
- type: entity
  parent: MCFire
  id: MCTileFireBlue
  components:
  - type: Sprite
    layers:
    - map: [ "base" ]
      state: blue_4
  - type: PointLight
    color: "#0a0aff"
  - type: RMCIgniteOnCollide
    intensity: 46 # burn_level = 46
    duration: 40
  - type: TileFire
    id: MCTileFireBlue
    duration: 40 # burn_time = 40
    extinguishInstantly: false
    patExtinguishMultiplier: 2
  - type: GenericVisualizer
    visuals:
      enum.TileFireLayers.Base:
        base:
          One: { state: blue_1 }
          Two: { state: blue_2 }
          Three: { state: blue_3 }
          Four: { state: blue_4 }

# Green Flame
- type: entity
  parent: MCFire
  id: MCTileFireGreen
  components:
  - type: Sprite
    layers:
    - map: [ "base" ]
      state: green_4
  - type: PointLight
    color: "#00ff00"
  - type: RMCIgniteOnCollide
    maxStacks: 10 # incendiary_strength = 10
    intensity: 18 # burn_level = 18
    duration: 12
    tileDamage:
      types:
        Heat: 1
  - type: TileFire
    id: MCTileFireGreen
    duration: 12 # burn_time = 12
    extinguishInstantly: false
    patExtinguishMultiplier: 2
  - type: GenericVisualizer
    visuals:
      enum.TileFireLayers.Base:
        base:
          One: { state: green_1 }
          Two: { state: green_2 }
          Three: { state: green_3 }
          Four: { state: green_4 }

