- type: entity
  abstract: true
  parent: [ MCItem, MCWeaponGun, RMCBaseAttachableHolder ]
  id: MCWeaponGrenadeLauncher
  components:
  - type: Item
    size: Large
  - type: Gun
    projectileSpeed: 50
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/grenade_launcher.ogg
    resetOnHandSelected: false
  - type: GunIFF
    enabled: true
  - type: RMCSelectiveFire
    baseFireModes:
    - SemiAuto
    recoilWielded: 2
  - type: ShootAtFixedPoint
    shootArcProj: true
    maxFixedRange: 8
  - type: OnShootTriggerAmmoTimer
    delay: 1
    beepInterval: 2
    initialBeepDelay: 0
    beepSound:
      path: /Audio/Effects/beep1.ogg
      params:
        volume: 5
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
        ents: []
  - type: RMCAmmoEject
    containerID: ballistic-ammo
    ejectSound:
      path: /Audio/_RMC14/Weapons/Guns/Reload/grenade_insert.ogg
      params:
        volume: -2
  - type: BallisticAmmoProvider
    whitelist:
      tags:
      - MCGrenade
    capacity: 1
    soundInsert:
      path: /Audio/_RMC14/Weapons/Guns/Reload/grenade_insert.ogg
  - type: AmmoCounter
  - type: Wieldable
  - type: GunRequiresWield
  - type: WieldableSpeedModifiers
    base: 0.5
    light: 0.69
    medium: 0.75
    heavy: 0.806
  - type: WieldDelay
    baseDelay: 0.8
  - type: Clothing
    slots:
    - back
    - suitstorage
  - type: RMCNameItemOnVend
    item: PrimaryGun
  - type: WieldedCrosshair
    rsi:
      sprite: _RMC14/Interface/MousePointer/explosive_mouse.rsi
      state: all
  - type: GunIgnorePrediction

- type: entity
  parent: [ MCWeaponGun, BaseWeaponLauncher ]
  id: MCWeaponLauncher
  abstract: true
  components:
  - type: Clothing
    quickEquip: true
    slots:
    - back
    - suitStorage
  - type: Gun
    fireRate: 0.83
    soundGunshot:
      path: /Audio/_RMC14/Weapons/Guns/Gunshots/m5_shoot.ogg
    resetOnHandSelected: false
  - type: BallisticAmmoProvider
    whitelist:
      tags:
      - RMCRocketAmmo84mm
    capacity: 1
    cycleable: true
    proto: RMCRocket84mm
    soundInsert:
      path: /Audio/_RMC14/Weapons/Guns/Cock/m5_ammo.ogg
  - type: ExplosionResistance
    damageCoefficient: 0
  - type: Wieldable
  - type: GunRequiresWield
  - type: RMCNameItemOnVend
    item: PrimaryGun
  - type: OnShootTriggerAmmoTimer
    delay: 0.2 # TODO RMC14 Make some way for rockets to explode when they stop, for shooting at the ground closer than max range.
    # This is a temporary hack to guarantee it will always go off after stopping even if it doesn't collide with anything.
    # Works for almost all gameplay purposes at least right now because even max range rockets are less than 0.2s and it's fast enough not matter.
  - type: ShootAtFixedPoint
    shootArcProj: false
  - type: WieldDelay
    baseDelay: 1.2
    preventFiring: true
  - type: IgnorePredictionHide
  - type: GunIgnorePrediction
  - type: WieldedCrosshair
    rsi:
      sprite: _RMC14/Interface/MousePointer/explosive_mouse.rsi
      state: all
