- type: entity
  parent: MCMeleeWeapon
  id: MCMeleeWeaponVali
  abstract: true
  components:
  - type: Tag
    tags: [ MCMeleeWeaponVali ]
  - type: MCWeaponVali
    allowedReagents:
    - MCBicaridine
    - MCKelotane
    - MCTricordrazine
    - MCTramadol
    - MCDexalin

- type: Tag
  id: MCMeleeWeaponVali
