- type: entity
  id: MCXenoNoMeleeBase
  abstract: true
  categories: [ MCContent ]
  components:
  - type: TunnelRenamer
  - type: MCXenoHeal
  - type: MCXenoPlasma
  - type: XenoAnnounceDeath
    message: mc-xeno-death
    color: "#459A62"
  - type: ShowHealthBars
    damageContainers:
    - Biological
  - type: Flammable
    fireSpread: false
    canResistFire: true
    resistDuration: 1
    # per second, scales with number of fire 'stacks'
    damage:
      types:
        MCBurn: 1
  - type: RMCSize
    size: Xeno
  - type: Tag
    tags:
    - DoorBumpOpener
    - MCDamageMelee
  - type: MobState
    allowedStates:
    - Alive
    - Critical
    - Dead
  - type: NightVision
    overlay: false
    drawFov: false
  - type: MCXenoSunder
  - type: UserInterface
    interfaces:
      # MC
      enum.MCXenoReagentSelectorUI.Key:
        type: MCXenoReagentSelectorBui
      enum.MCXenoPortalPlacerUI.Key:
        type: MCXenoChoosePortalBui
      enum.MCXenoPlantingWeedsUI.Key:
        type: MCXenoChooseWeedsBui
      enum.MCXenoBlessingsUiKey.Key:
        type: MCXenoBlessingsBui
      # RMC
      enum.XenoEvolutionUIKey.Key:
        type: XenoEvolutionBui
      enum.XenoDevolveUIKey.Key:
        type: XenoDevolveBui
      enum.XenoWatchUIKey.Key:
        type: XenoWatchBui
      enum.XenoChooseStructureUI.Key:
        type: XenoChooseStructureBui
      enum.XenoPheromonesUI.Key:
        type: XenoPheromonesBui
      enum.XenoOrderConstructionUI.Key:
        type: XenoOrderConstructionBui
      enum.XenoFruitChooseUI.Key:
        type: XenoFruitChooseBui
      enum.XenoWordQueenUI.Key:
        type: XenoWordQueenBui
      enum.TacticalMapUserUi.Key:
        type: TacticalMapUserBui
      enum.XenoReserveParasiteChangeUI.Key:
        type: ReserveParasitesBoundUserInterface
      enum.XenoParasiteGhostUI.Key:
        type: XenoParasiteGhostBui
        requireInputValidation: false
      enum.DialogUiKey.Key:
        type: DialogBui
  - type: TacticalMapUser
    actionId: RMCActionOpenTacticalMapXeno
    xenos: true
    liveUpdate: true
  - type: TacticalMapLiveUpdateOnOvi
    enabled: false

- type: entity
  parent: MCXenoNoMeleeBase
  id: MCXenoUnactiveBase
  abstract: true
  components:
  - type: MeleeWeapon
    attackRate: 1.25
    autoAttack: true
    widePrimary: true
    altDisarm: false
    altHeavy: false
  - type: XenoClaws
    clawType: Sharp
  - type: CombatMode
    canDisarm: false

- type: entity
  parent: MCXenoUnactiveBase
  id: MCXenoBase
  abstract: true
  components:
  - type: MCXenoBiomass
  - type: MCXenoPsydrain
  - type: ActiveInputMover
  - type: MCXenoDamageVisuals

