- type: entity
  parent: MCItem
  id: MCAutoInjector
  name: auto injector
  description: An auto injector.
  abstract: true
  components:
  - type: Tag
    tags:
    - MCAutoInjector
  - type: Appearance
  - type: Sprite
    sprite: _RMC14/Objects/Medical/auto_injectors.rsi
    layers:
    - state: autoinjector
    - state: autoinjector1
      map: [ "enum.SolutionContainerLayers.Fill" ]
      visible: false
  - type: Item
    size: Small
  - type: Hypospray
    solutionName: pen
    injectSound: /Audio/_RMC14/Medical/hypospray.ogg
    transferAmount: 10
    injectOnly: true
    onlyAffectsMobs: true
    canContainerDraw: true
  - type: SolutionContainerManager
    solutions:
      pen:
        maxVol: 30
  - type: SolutionContainerVisuals
    maxFillLevels: 3
    fillBaseName: autoinjector
    emptySpriteName: autoinjector
    changeColor: true
  - type: IconLabel
    textColor: White
    storedOffset: 0, 12
  - type: RMCSmartFridgeInsertable
  - type: ExaminableSolution
    solution: pen

- type: Tag
  id: MCAutoInjector
