- type: entity
  parent: BaseBullet
  id: MCBullet
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _MC/Objects/Weapons/Guns/Ammunition/Projectiles/bullet.rsi
    layers:
    - state: base
      shader: unshaded
  - type: BulletholeGenerator
  - type: RMCBullet
  - type: RMCProjectileAccuracy
  - type: Projectile
    soundHit:
      path: /Audio/_RMC14/Bullets/bullet_impact1.ogg
